### ISSUE TITLE
Link to details expired 

### ISSUE THREAD

**Issue by prh-t** [royshil/CurveMatching#1]
The original link 
[http://www.morethantechnical.com/2012/12/26/2d-curve-matching-w-code/](http://www.morethantechnical.com/2012/12/26/2d-curve-matching-w-code/)
seems to be outdated, this link might be the correct one: 
[https://www.morethantechnical.com/2012/12/27/2d-curve-matching-in-opencv-w-code/](https://www.morethantechnical.com/2012/12/27/2d-curve-matching-in-opencv-w-code/)

**Comment by royshil** [comment]
oops. fixed
